### ISSUE TITLE
Swift could not resolve dependency

### ISSUE THREAD

**Issue by martinvw** [securing/IOSSecuritySuite#10]
Thanks for this project, I have a small issue.

When following the README and using the below fragment to add it as a dependency:

```
.package(url: "https://github.com/securing/IOSSecuritySuite.git", from: "1.4.0")
```

I get the following error:

```
Fetching https://github.com/securing/IOSSecuritySuite.git
Fetching https://github.com/apple/example-package-deckofplayingcards.git
error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
    https://github.com/securing/IOSSecuritySuite.git @ 1.4.0..<2.0.0
```
Looking at the actual releases I see releases with 1.4 instead of 1.4.0. However, changing it to 1.4 will trigger the error:

> Invalid semantic version string '1.4'

**Comment by r3ggi** [comment]
Thanks for the info, updated! 👏🏻

**Comment by martinvw** [comment]
Great thanks for the rapid response!
