### ISSUE TITLE
advanced method to detect rootless and root jailbreaks

### ISSUE THREAD

**Issue by ghost** [securing/IOSSecuritySuite#100]
#include <sys/mount.h>

struct statfs buf;
statfs("/", &buf);
NSLog(@"%s", buf.f_mntfromname);
char* prefix = "com.apple.os.update-";
if(strstr(buf.f_mntfromname, prefix)) {
    NSLog(@"未越狱, 设备唯一识别码=%s", buf.f_mntfromname+strlen(prefix));
} else {
    NSLog(@"已越狱, 没有设备唯一识别码");
}

this is a method by the H5GG dev

**Comment by r3ggi** [comment]
hey! Thanks for your suggestion

**Comment by r3ggi** [comment]
Hey! I checked that technique on a non-jailbroken iPhone and on Dopamine jailbroken iPhone. Both have ID in the `buf.f_mntfromname` - so the code you provide seems not to work :(

**Comment by r3ggi** [comment]
Hey! I checked that technique on a non-jailbroken iPhone and on Dopamine jailbroken iPhone. Both have ID in the `buf.f_mntfromname` - so the code you provide seems not to work :(
