### ISSUE TITLE
Question: is there a free Obfuscate tool ? 

### ISSUE THREAD

**Issue by X901** [securing/IOSSecuritySuite#102]
Hi, 
Thank you for awesome tools
I notice you recommended [Swiftshield](https://github.com/rockbruno/swiftshield)
But The issue is he stop working on that project and not recommended using it in Production App

> Don't use this tool for production apps. I gave up on keeping this tool updated because every Swift release breaks SourceKit in a different way. It's probably really broken and is only useful as a way for you to learn more about obfuscation and SourceKit.

Is there other Free tools that do the same thing ?

**Comment by r3ggi** [comment]
Hey!

Sorry, I don't have any free obfuscation tool to recommend. :(
