### ISSUE TITLE
Activator URL scheme detected

### ISSUE THREAD

**Issue by kyledold** [securing/IOSSecuritySuite#107]
We seem to be seeing a jump in our jailbreak detections related to "activator://" URL scheme detected. 
These devices seem to be legitimate and not jailbroken, I'm wondering if anybody else is seeing this? and should we remove this check?

Our app is UK based and we're I'm wondering if there is an app on AppStore that has registered this URL which is causing the false detections.

**Comment by r3ggi** [comment]
Thx for the info, it should be fixed in https://github.com/securing/IOSSecuritySuite/releases/tag/1.9.11

**Comment by tymurmustafaiev** [comment]
Hey @kyledold, have you found which app caused this false detection?

**Comment by kyledold** [comment]
@tymurmustafaiev unfortunately no, we never found the route cause of what was trigger this.

@r3ggi  what was the fix?
