### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by niji-mathieu-viel** [securing/IOSSecuritySuite#113]
Hi guys.

I think that the library may be impacted by this new rule by Apple; from what I understand, as the library is not collecting any personal data, an empty manifest + podspec / package.swift setup should do the trick (?)

Third-party SDKs should include a privacy manifest by Spring according to Apple new requirements :
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc

Thanks.

**Comment by LongXiangGuo** [comment]
<img width="857" alt="Screenshot 2024-02-27 at 10 25 48" src="https://github.com/securing/IOSSecuritySuite/assets/16632821/d61b05e0-ec21-4e8c-9820-b24a419d401d">


> Hi guys.
> 
> I think that the library may be impacted by this new rule by Apple; from what I understand, as the library is not collecting any personal data, an empty manifest + podspec / package.swift setup should do the trick (?)
> 
> Third-party SDKs should include a privacy manifest by Spring according to Apple new requirements : https://developer.apple.com/support/third-party-SDK-requirements/ https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc
> 
> Thanks.

Yes, I think. See https://github.com/fluttercommunity/plus_plugins/pull/2582/files

**Comment by ObjectiveCesar** [comment]
As far as I know, Apple wanted to send out emails starting March, 13th when uploading new builds to App Store Connect if any framework is missing any mandatory info including the privacy manifest.
We did upload multiple builds of our app including IOSSecuritySuite and there have been now issues so far.

**Comment by r3ggi** [comment]
Hey! I'm working on a big ISS update, so I think I will be able to implement this privacy manifest this week

**Comment by claypark12** [comment]
Thank you for your response @r3ggi , is there any update regarding the issue?

**Comment by r3ggi** [comment]
done :-)

**Comment by ObjectiveCesar** [comment]
So this new license applies to v 2.0+ ?
