### ISSUE TITLE
Jailbreak Detection on Dopamine

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [securing/IOSSecuritySuite#120]
Hi team. Could you kindly play a game with Dopamine?😎
https://ellekit.space/dopamine/

**Comment by r3ggi** [comment]
Hmm, doesn't ISS detect Dopamine jailbroken iOS? On my test iPhone it works

**Comment by jinaiyuanbaojie** [comment]
> Hmm, doesn't ISS detect Dopamine jailbroken iOS? On my test iPhone it works 

There is menu named "Hide Jailbreak". What this menu is enable, we will be bypassed.
Could you kindly have a try🤔

**Comment by r3ggi** [comment]
Dopamine hide jailbreak detection implemented in 2.1.0 🚀

**Comment by jinaiyuanbaojie** [comment]
> Dopamine hide jailbreak detection implemented in 2.1.0 🚀

Amazing Bro
