### ISSUE TITLE
App Hanging on JailbreakChecker.checkDYLD

### ISSUE THREAD

**Issue by KimMylerMedia** [securing/IOSSecuritySuite#121]
Hi, I am receiving app hanging warnings from the JailbreakChecker.checkDYLD. 

Added the stack trace below for further information.

<img width="678" alt="Screenshot 2024-04-15 at 09 58 02" src="https://github.com/securing/IOSSecuritySuite/assets/115804089/9876abb6-f827-4b5d-8c61-e540905150f4">

Thank you in advance!

**Comment by r3ggi** [comment]
Sorry, I can't reproduce it. Feel free to reopen this ticket when you identify a reliable way to reproduce it
