### ISSUE TITLE
False positives with /private/var/users

### ISSUE THREAD

**Issue by VeronikaHrbacova** [securing/IOSSecuritySuite#126]
Hello, we seem to have some false positives on shared iPad devices, where we detect the folder `/private/var/users` even though these devices are not jailbroken. We are wondering whether it could be something about the way these devices are wiped/restored. Do you have any experience with such false positives? Thank you

**Comment by r3ggi** [comment]
Hey!
So far I didn't experience such false positive. Feel free to reopen this ticket when you identify reproducible behaviour

**Comment by danielkono** [comment]
It seems that on [Apple Shared iPad ](https://support.apple.com/de-de/guide/deployment/dep9a34c2ba2/web)setup the checkExistenceOfSuspiciousFiles for `/private/var/users` triggers a false positive. (FileManager.default.fileExists(atPath: /private/var/users) => true)
Can reproduce it with an Apple iPad (7th Gen) with iPadOS 18.4.1 [22E252]

Tested on another Apple iPad (7th Gen) with iPadOS 18.5 without Shared iPad setup and plugin reports expected value.

Please reopen.
