### ISSUE TITLE
False positive jailbrake detection in iOS app that supports macOS using Catalyst.

### ISSUE THREAD

**Issue by BalkiX** [securing/IOSSecuritySuite#127]
Run iOS app on macOS. IOSSecuritySuite.amIJailbrokenWithFailMessage() will return that device is jailbroken with this message:

This device is jailbroken
Because: Suspicious file exists: /bin/bash, Suspicious file can be opened: /bin/bash, Fork was able to create a new process (sandbox violation)

Therefore jailbrake detection needs to be turned off for apps supporting macOS. As consequence on iOS jailbrake detection can be bypassed by using "M1 Mac Spoof"

**Comment by leyvaje** [comment]
facing same issue here

**Comment by r3ggi** [comment]
Hey!

ISS focuses on iOS/iPadOS detections. There is a clear sentence in the README:

```
Notice
iOS Security Suite is meant to be used on iOS/iPadOS. It should not be used on Macs with Apple Silicon.
```

If you have an app that uses Mac Catalyst - please detect if it's running on macOS and do not perform ISS checks. macOS has totally different attack surface than iOS so the ISS will not be effective on that platform.
