### ISSUE TITLE
Simulator False Positives

### ISSUE THREAD

**Issue by undeaDD** [securing/IOSSecuritySuite#13]
**Issue:** Calling this function on an Emulated Device returns two "False Positives"

`IOSSecuritySuite.amIJailbrokenWithFailMessage()`

> Suspicious file exists: /bin/bash, Suspicious file can be opened: /bin/bash

> Fork was able to create a new process (sandbox violation) 

**Proposal:** Maybe skip those two Checks if its run on an Emulated Device ?
`IOSSecuritySuite.amIRunInEmulator()`

**Tested via: iPhoneXS iOS 12.2 Simulator | XCode 11.3.1**

**Comment by r3ggi** [comment]
Thanks, fixed in the https://github.com/securing/IOSSecuritySuite/commit/48ee05c8e0d447e2a0f2cb9b78bc342abe8d52ae

**Comment by r3ggi** [comment]
Thank you very much also for great ideas. I've just added you to ISS' special thanks section 😉 https://github.com/securing/IOSSecuritySuite/commit/157cd00ba87dc6cc28153b3570e310cfb8515cf7
