### ISSUE TITLE
Jailbreak is detected on all normal devices 

### ISSUE THREAD

**Issue by EAlsharkawy** [securing/IOSSecuritySuite#14]
All non jailbroken devices got jailbreak message because of `ExistenceOfSuspiciousFiles` of this path "/usr/sbin/".

kindly check it

**Comment by r3ggi** [comment]
Hey,

Thanks! In the last commit I made a typo leading to that false positive. Fixed in  https://github.com/securing/IOSSecuritySuite/commit/5abdf9c2e6203b088a4b9fc3e69a7bf6a2eb0231
