### ISSUE TITLE
Attaching Debugger still possible with -waitfor option in debugserver

### ISSUE THREAD

**Issue by bobmosh** [securing/IOSSecuritySuite#15]
Hey guys,

I am currently playing around with this and found out that calling the `denyDebugger()` does only partially solve the issue. Of course this can be bypassed by writing into memory, but still, whenever I run` debugserver *:1234 -waitfor MyApp` I am still able to run the app because the wait option interrupts directly on the launch screen, even before the init call of the AppDelegate.swift.

Whenever I attach the debugger and run `continue`, the app crashes thanks to the denied debugger access inside of the init call of AppDelegate. However this opens up vulnerabilities, since I am still able to interact the debugger as long as I don't let the app run the denyDebugger() function.

Is this something I will just have to live with? Seems to make the function suite ineffective in my eyes, but I'm ready to be proven wrong. :)

Cheers,
bob_mosh

**Comment by r3ggi** [comment]
Hey Bob!

As ISS is a library that is intended to be included in applications, the `denyDebugger()` method will work after it is called. The behaviour you discovered is thus expected. If you have an idea of how it can be improved - let me know!

Please also remember that an attacker always wins vs client-side security checks. Even if you are able to deny debugger somehow earlier, the attacker can disassemble your app, turn all the checks off, re-sign the app, and install on the device.
