### ISSUE TITLE
Question on mach-o hash value

### ISSUE THREAD

**Issue by prashantLalShrestha** [securing/IOSSecuritySuite#30]
I can get a machOFileHashValue of main executable from code.  But how do I get the value to store in server which will be later retrieved from app? Because every build generates new mach-o value.

**Comment by r3ggi** [comment]
Hey!

The algorithm is as follows:
1. Build the application
2. Calculate the SHA256 hash of the executable (using for example `shasum -a 256 /path/to/executable`)
3. Save the hash along with the version on the server

Then on the application side:
1. SHA256 hash is calculated using `IOSSecuritySuite.getMachOFileHashValue`
2. The app gets from the server the valid hash
3. The app verifies if `hashFromTheServer == hashCalculatedInTheApp`

**Comment by prashantLalShrestha** [comment]
@r3ggi Thanks for replying. 
Is this the executable file of app? It's from the archived file

<img width="581" alt="Screen Shot 2020-10-16 at 16 05 36" src="https://user-images.githubusercontent.com/31603998/96247551-ffd62700-0fc9-11eb-8160-758110a1f62b.png">

**Comment by r3ggi** [comment]
Correct, this is the executable you are looking for :-)

**Comment by prashantLalShrestha** [comment]
@r3ggi I'm getting different value on distribution on testflight. 
I archived the project.
-> uploaded in my developer account. + extracted the ipa.
-> generate the sha from executable file.
But it's not matching with the app generated value.

**Comment by prashantLalShrestha** [comment]
the hash generated from `shasum -a 256 /path/to/executable` is not matching with the hash from `IOSSecuritySuite.getMachOFileHashValue`

**Comment by r3ggi** [comment]
Oh, sorry, SHA256 hash of the full file is used with `embedded.mobileProvision` file.

The `IOSSecuritySuite.getMachOFileHashValue` calculates the SHA256 hash of the __TEXT,__text section as we want to know if the code loaded into the memory has not been tampered.
So, in order to calculate that hash on your mac you can use the following commands:

```sh
otool -l /path/to/file  (save offset and size)
```

and then:

```sh
dd if=./FrameworkClientApp ibs=1 skip=<offset> count=<size> | shasum -a 256
```

**Comment by prashantLalShrestha** [comment]
@r3ggi this worked as expected. Thanks

**Comment by kofsiwon** [comment]
I can't access getMachOFileHashValue() in Release, But can in Debug
Type 'IOSSecuritySuite' has no member 'getMachOFileHashValue'
What't wrong?

**Comment by r3ggi** [comment]
Keep in mind that `IOSSecuritySuite.getMachOFileHashValue()` is defined in an extension for arm64. Make sure you test it on arm64 device.

**Comment by kofsiwon** [comment]
something is weird. my device is iPhone X and
I can call getMachOFileHashValue in Debug, but not in Release..
I had to switch [Build Active Architecture Only > Release: No] to Yes
Then I could call it.

Even in Release, I get true with this code
```
if IOSSecuritySuite.amITampered([.bundleID("..."),
                                                   .mobileProvision("..."),
                                                   .machO("IOSSecuritySuite", "...")]).result 
```

As a result, I got machO hash with Build Active Architecture Only > Release: Yes
And input the hash into .machO(...)
My solution could fail in armv7s device?? 
I don't have armv7s device, and My app's minimum target iOS 10

thank you

**Comment by vocaeq** [comment]
Hello @kofsiwon,
If the minimum target version is set to iOS 10 and if you try to build a release version, Xcode will try to build a 32bit version of the application which is not supported by this particular function, and thus building will fail. armv7s architecture is of iPhone 5 which is a 32bit device and it is not supported anymore on iOS 11 and above. To solve your problem, simply change the minimum target to iOS 11. 

Hope this answered your question!

**Comment by TommyLeong** [comment]
> Oh, sorry, SHA256 hash of the full file is used with `embedded.mobileProvision` file.
> 
> The `IOSSecuritySuite.getMachOFileHashValue` calculates the SHA256 hash of the __TEXT,__text section as we want to know if the code loaded into the memory has not been tampered.
> So, in order to calculate that hash on your mac you can use the following commands:
> 
> ```shell
> otool -l /path/to/file  (save offset and size of the __TEXT,__text section)
> ```
> 
> and then:
> 
> ```shell
> dd if=/path/to/file ibs=1 skip=<offset> count=<size> | shasum -a 256
> ```

Hello @r3ggi , may I know what is the `/path/to/file` that is expected for the following command? `otool -l /path/to/file`
I am getting `test.ipa: is not an object file` while running `otool -l test.ipa` I suppose the file path for `otool` is the **Unix executable** within the ipa itself?

Here's what I did, would be helpful if you could let me know I'm doing it right.

### Look for Unix Executable file ###
1. Unzip the .ipa
2. Go into the payload folder, right click on the app, click on `Show Package Contents`
3. I should see the **Unix executable** with my app name (Example, "test" is the name in this case)

### Running otool command ###
1. `otool -l /Users/tester/Desktop/test.app/test`
2. Then I look for value of `offset` and `size`
<img width="141" alt="Screenshot 2021-01-29 at 5 53 38 PM" src="https://user-images.githubusercontent.com/9990179/106260023-ed22ed80-625a-11eb-87ae-31f046f0b9c3.png">
3. Save the value somewhere

### Getting SHA256 result ###
1. Run the command`dd if=test.ipa ibs=1 skip=<offset> count=<size> | shasum -a 256` (with my OFFSET and SIZE value replaced)
2. I'm getting the SHA256 result.

**Comment by r3ggi** [comment]
Hey @TommyLeong,

Answering your questions:

> Hello @r3ggi , may I know what is the /path/to/file that is expected for the following command? otool -l /path/to/file
I am getting test.ipa: is not an object file while running otool -l test.ipa I suppose the file path for otool is the Unix executable within the ipa itself?

IPA is just a compressed ZIP archive. You have to use `otool` on an executable file that is inside of the unpacked IPA.

Your instruction looks correct. 😉 (I think it's better to call the executable file as "Mach-O executable" rather than "Unix Executable")

**Comment by kwstasna** [comment]
In the example of @TommyLeong what `imageName` should we write in swift code to check the machO with  `IntegrityChecker.amITampered` ? @r3ggi

**Comment by r3ggi** [comment]
The `imageName` passed in `IOSSecuritySuite.amITampered(.machO(imageName, hash))` is a name of Mach-O file loaded into memory, for example name of a loaded framework.

**Comment by kwstasna** [comment]
Oh ok, so it doesn't matter what framework we write there, it should be one of the loaded ones.

Thanks a lot for the clarification !

**Comment by pkozielecki** [comment]
@r3ggi I followed the guide described by @TommyLeong and I consistently get hash value that does not match one obtained using `IOSSecuritySuite.getMachOFileHashValue(.default)`; I tested it on iOS 15.2 and 14.7. 
I use `IOSSecuritySuite 1.9.1`. The app is signed using `Enterprise` provisioning profile (if that makes any difference).

**Comment by r3ggi** [comment]
Hey,

Please provide the code snippet you used to calculate these 2 hashes

**Comment by pkozielecki** [comment]
Sure:
1. Inside the app: `IOSSecuritySuite .getMachOFileHashValue(.default)`
2. Outside the app: 
a) I unpack `ipa` content and call `otool` on an executable file: `otool -l path_to_ipa_content/Payload/MyApp.app/MyApp`
b) I extract `size` and `offset` from `__text` section.
c) I call `dd` to calculate hash value: `dd if=path_to_ipa ibs=1 skip=offset count=size | shasum -a 256`

Just to be sure, I converted `size` into `decimal` number - got the same result

**Comment by r3ggi** [comment]
Hey Pawel,

I've just reproduced the whole algorithm and in my case it works :-)

```
wregula@sTests ISStests.app % dd if=./ISStests ibs=1 skip=26408 count=0x0000000000030560 | shasum -a 256
197984+0 records in
386+1 records out
197984 bytes transferred in 0.665541 secs (297478 bytes/sec)
f7c511de7509d6cdc58bd1b071f29a53bb9fd82ba738591a93b2af60d5a43b43  -
```

and the ISS returns:

```
Optional("f7c511de7509d6cdc58bd1b071f29a53bb9fd82ba738591a93b2af60d5a43b43")
```

**Comment by pkozielecki** [comment]
In my case it is:
![Screenshot 2022-01-17 at 13 00 31](https://user-images.githubusercontent.com/15871616/149768526-bb9e2af4-14f5-49b2-adc8-7c2c7a123553.png)
and then:
![Screenshot 2022-01-17 at 13 19 17](https://user-images.githubusercontent.com/15871616/149768727-f395fbdd-e077-4342-b3ad-e3917d44793e.png)
which gives me: `6abd70a98474c43dbb89af7ffea7951d078b03e265c28afcf17b1659453e299b`

Inside the app I get:
`b2c459cbdfc77bc3de1690c113a9365d2fa07ece981d916f3d10eccdda92159f`

Could it have any connection with the fact that `ISS` is linked statically and the app is distributed as an `Enterprise` app

**Comment by r3ggi** [comment]
Paweł, 

As I responded in https://github.com/securing/IOSSecuritySuite/issues/30#issuecomment-769709570 : 

> You have to use otool on an executable file that is inside of the unpacked IPA.

`dd` also accepts that MachO executable file in the `if` parameter. IPA is just a zip :-)

**Comment by r3ggi** [comment]
Great, good luck!

**Comment by GManShen** [comment]
Hi, maybe a dumb question, the ipa which you are using is it the store build ipa or does that have any impact on the checksum. i am not able to match the checksum.
