### ISSUE TITLE
Question for architecture

### ISSUE THREAD

**Issue by MarMarIV** [securing/IOSSecuritySuite#31]
Is there any way how to target on ARMv7s architecture?

![Capture - Copy](https://user-images.githubusercontent.com/10964247/98624851-e4331780-230e-11eb-9cee-929d4607b293.PNG)

Thanks

**Comment by vocaeq** [comment]
Hello @MarMarIV,
ARMv7s is 32bit architecture which is not supported by Apple since iOS 10 and so ISS does not support ARMv7s anymore. 
If you encounter troubles with compilation, change minimum version in xcode to iOS 11.
Hope it answers you question!

**Comment by MarMarIV** [comment]
> Hello @MarMarIV,
> ARMv7s is 32bit architecture which is not supported by Apple since iOS 10 and so ISS does not support ARMv7s anymore.
> If you encounter troubles with compilation, change minimum version in xcode to iOS 11.
> Hope it answers you question!

Ok. So se should update from iOS 10 to higher version

Thanks
