### ISSUE TITLE
Filemanager question

### ISSUE THREAD

**Issue by kwstasna** [securing/IOSSecuritySuite#36]
Hello.
As I see in your code you are using `FileManager.default.fileExists` to determine if there is any path that can be opened.
And you also have an array of paths that you want to check.

Isn't it really easy for the most common AntiJB detection tweaks to overwrite this function and return false when something like this list of text appears?

ex. https://github.com/XsF1re/FlyJB-X/blob/9476f70948663e00e0769bf643592fa3f50b84be/Tweaks/ObjCHooks.xm#L56

How do you approach these cases?

**Comment by r3ggi** [comment]
Hey!

Thank you for your question. `ISS` implements a lot of different methods to detect if it's run on a jailbroken device. Even if common anti-jb-detectors block the `FileManager.default.fileExists`-based checks, `ISS` will be still able to operate.
