### ISSUE TITLE
Anti MSHook does not work?

### ISSUE THREAD

**Issue by MetaSlave** [securing/IOSSecuritySuite#39]
I wanted to use the Anti MSHook capability and decided to test out its effectiveness by writing a Theos Tweak using MSHook to hook a swift function that I wrote in an iOS application. I followed the implementation details in the README. However it seems that the Anti MSHook functions, amIMSHooked and denyMSHook both do not work as my tweak is still able to modify the function. Am I doing something wrong?

Swift Code under ViewController Class :
```
func CoolBeans(value: Int) -> Int{ return value }
typealias FunctionType = @convention(c) (Int) -> (Int)
func getSwiftFuncAddr(_ function: @escaping FunctionType) -> UnsafeMutableRawPointer { return unsafeBitCast(function, to: UnsafeMutableRawPointer.self)}
let funcAddrDetect = getSwiftFuncAddr(CoolBeans)
print(IOSSecuritySuite.amIMSHooked(funcAddrDetect))
```

Theos Tweak :
```
static int (*orig_ViewController_CoolBeans)(int) = NULL;
int hook_ViewController_CoolBeans() { // Do Something Different from Original Function }
%ctor {
  %init(ViewController = objc_getClass("mshook.ViewController"));
  MSHookFunction(MSFindSymbol(NULL,"_$s6mshook14ViewControllerC11viewDidLoadyyF9CoolBeansL_5valueS2i_tF"),
  (void *)hook_ViewController_CoolBeans,
  (void **)&orig_ViewController_CoolBeans);
}
```
Not sure whether the following is relevant but, logging the loading of my tweak and when the getSwiftFuncAddr() is called, I found out that the tweak loads first which means that the function has already been tampered with by the time I call getSwiftFuncAddr(). I also logged the "CoolBeans" function address from both my tweak and the the output of getSwiftFuncAddr() and there is a difference in both addresses.

**Comment by r3ggi** [comment]
Hey @TannerJin, could you look at this issue please? 😉

**Comment by TannerJin** [comment]
Hey, @MetaSlave  `typealias FunctionType = @convention(c) (Int) -> (Int) ` should be `typealias FunctionType = @convention(thin) (Int) -> (Int)`

**Comment by MetaSlave** [comment]
Thank you, that did the trick!
