### ISSUE TITLE
idea: detect m1 mac enviroment ^^

### ISSUE THREAD

**Issue by undeaDD** [securing/IOSSecuritySuite#41]
`if #available(iOS 14.0, *), ProcessInfo.processInfo.isiOSAppOnMac { ... }`

not sure if this would be helpfull. but i thought why not :D 
( too lazy to create a PR though ^^ sry )

**Comment by r3ggi** [comment]
Hey,

Haha, thx for that idea. 🙏🏼🚀

**Comment by rafabertholdo** [comment]
Was this aready implemented? I made my app available for mac m1 on appstore but i'm getting "Suspicious file exists: /bin/bash"

**Comment by r3ggi** [comment]
Hey,

For now we don't have plans to implement that feature.

If your app is available also on M1 Macs, I'd suggest verifying that in the runtime and then launching jailbreak checks or not.
