### ISSUE TITLE
FileManager.default.fileExists - Check if its Hooked

### ISSUE THREAD

**Issue by kwstasna** [securing/IOSSecuritySuite#42]
Hello.

What I'm trying to do is to check if the `FileManager.default.fileExists` function is a hooked function.
 
When I try with the following code

```
        typealias FunctionType = @convention(thin) (String) -> (Bool)
        func getSwiftFunctionAddr(_ function: @escaping FunctionType) -> UnsafeMutableRawPointer {
            return unsafeBitCast(function, to: UnsafeMutableRawPointer.self)
        }
        
        
        let funcAddr = getSwiftFunctionAddr(FileManager.default.fileExists)
        
        
        IOSSecuritySuite.amIMSHooked(funcAddr)
```

I get an error here

`let funcAddr = getSwiftFunctionAddr(FileManager.default.fileExists)`

**INTERNAL ERROR: feature not implemented: nontrivial thin function reference**

Anyone knows what is this and if there is any solution to actually check if this function is hooked?

Thanks a lot !

**Comment by r3ggi** [comment]
Hey!

Current implementation of `MSHook` module does not support system methods for now. 😢
