### ISSUE TITLE
Missing socket close, open files problem

### ISSUE THREAD

**Issue by hellpf** [securing/IOSSecuritySuite#44]
https://github.com/securing/IOSSecuritySuite/blob/d61af467aa64fd5a0d2bf8e9cdfe4762160fffeb/IOSSecuritySuite/ReverseEngineeringToolsChecker.swift#L92

Please add here following code to clean up all opened files.

```
        defer {
            close(sock)
        }

```

**Comment by r3ggi** [comment]
Hey,

Thanks for spotting that!

**Comment by r3ggi** [comment]
Fixed in 1.9.1. Thanks! 🚀
