### ISSUE TITLE
checkFork crash at iOS 15 device

### ISSUE THREAD

**Issue by paradiseduo** [securing/IOSSecuritySuite#50]
![image](https://user-images.githubusercontent.com/14846965/131797095-d996f2a3-4a5c-4b4e-b14e-1abdebb8d2ef.png)

**Comment by vocaeq** [comment]
Hi, I tried to compile code using the newest version of Xcode Beta and deploy app on newest iOS 15 Beta, but crash did not occur on my device. Do you still have this issue? Could you provide code that generated the crash?

**Comment by paradiseduo** [comment]
still crash
![image](https://user-images.githubusercontent.com/14846965/133185160-27519eed-a3c0-4d76-a686-62d1acaff190.png)

![image](https://user-images.githubusercontent.com/14846965/133185198-abf0ef39-b61f-4b5a-ac25-7773104d78c6.png)

**Comment by paradiseduo** [comment]
![image](https://user-images.githubusercontent.com/14846965/133185278-45f72f0f-20e5-4e59-9e8f-ea6854199d49.png)

**Comment by paradiseduo** [comment]
now I ues this code in pruduct, iOS 15 has no crash.
![image](https://user-images.githubusercontent.com/14846965/133185543-83a30fc7-ed69-4705-9197-29977b9fa062.png)

**Comment by paradiseduo** [comment]
I guess the app permissions in the development environment are different from those in the production environment.
