### ISSUE TITLE
Enquiry on HideJB Detection

### ISSUE THREAD

**Issue by keithoys** [securing/IOSSecuritySuite#55]
Dear Developers,

I'm enquiring on this line: https://github.com/securing/IOSSecuritySuite/blob/0205bffb0eba6e051e6971ea9bc49ac142f29a88/IOSSecuritySuite/JailbreakChecker.swift#L319

Could you shed some light on the full path of a suspiciousLibrary? I'm interested to know in the case of the "/.file" for detection against HideJB.

Appreciate it.
Thank you!

**Comment by r3ggi** [comment]
Hey @keithoys,

This improvement was a reaction to https://github.com/securing/IOSSecuritySuite/pull/19 . If you want to know what libraries HideJB hides you have to do some reverse engineering - I didn't check that.

**Comment by fnxpt** [comment]
If Im not mistaken they rename the hidejb related dylib files into this /.file
