### ISSUE TITLE
Got AppStore rejected

### ISSUE THREAD

**Issue by chongsawad-nice** [securing/IOSSecuritySuite#56]
Hi All, 
Recently I updated library from 1.7.1 to 1.9.1 and submitted to AppStore review on Nov 19, 2021.
It detected jail broken device from AppStore review team causing App was rejected due to showing error screen (we implemented it to present suspicious device detection)

Here is device info
- Device type: iPhone 
- OS version: iOS 15.1

```
Podflie.lock
- IOSSecuritySuite (1.9.1)
```

Here is code snippet 
```
var isSuspiciouDevice: Bool {
    let amIDebugged = IOSSecuritySuite.amIDebugged() ? true : false
    let amIReverseEngineered = IOSSecuritySuite.amIReverseEngineered() ? true : false
    let jailbreakStatus = IOSSecuritySuite.amIJailbrokenWithFailMessage()
    return (jailbreakStatus.jailbroken || amIReverseEngineered || amIDebugged)
  }
```

Unfortunately, we do not track `jailbreakStatus.failMessage` from user's device. So now I would like to ask everyone has this issue or not.

We submitted v.1.9.1 before (around Nov 5, 2021) but had no issue.  So it might be some changes from AppStore Review team ?

**Comment by GManShen** [comment]
Hi there, Did your app got approved?

**Comment by r3ggi** [comment]
Hey @chongsawad-nice,

That's weird. I haven't heard about App Store rejection from anyone else. Could you change the logic flow a bit and log the `failMessage`? Maybe `amIDebugged()` raises the prompt as they may use debugger attached during the manual review process.

**Comment by r3ggi** [comment]
as there are no new information from others that ISS causes App Store rejection, I'm closing this ticket for now
