### ISSUE TITLE
Is it expected to see -canOpenURL: failed for URL in the console?

### ISSUE THREAD

**Issue by philosopherdog** [securing/IOSSecuritySuite#61]
I'm seeing console log: `-canOpenURL: failed for URL: "undecimus://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"` for all of the urls defined in `LSApplicationQueriesSchemes` in the `ReadMe`.  Is this expected?

**Comment by izmcm** [comment]
Yes, this is completely normal if the app is not installed on the mobile. If this is happening even with the app installed, you must make sure that you are putting the urls in the app's Info.plist

**Comment by philosopherdog** [comment]
I have added the urls to Info.plist. What do you mean "app is not installed on mobile"? I'm seeing this as a console dump for the simulator. Is this expected? Thanx

**Comment by izmcm** [comment]
`canOpenURL` checks if the app exists on your phone. In this case, the library checks for specific apps linked to jailbreaking the device. You see this log when running code in the simulator because the simulator does not have any of these applications.
