### ISSUE TITLE
Major Jailbroken issue

### ISSUE THREAD

**Issue by himanshujindal8** [securing/IOSSecuritySuite#62]
Hi Team,

We have been using your SDK from past 2 years and recently our customers have complained regarding jailbreak issue. 
They complained that they are getting "Jailbreak error: cydia://" on their app, even their device is also not jailbroken.

We have tested on our end as well. There is one app on Appstore which is causing this error.
App link: https://apps.apple.com/ng/app/realconnect-dhre/id1346538794
When we are installing the above application into our device, its giving "cydia://" is installed as its checking for "cydia://" url scheme. 

Please help us to know the root cause as we are loosing customers.

Regards,
Himanshu Jindal

**Comment by r3ggi** [comment]
Hey Himanshu,

Wow, I'm totally surprised that there is an app in the official App Store that has the cydia:// URL scheme registered. I was able to confirm your issue.

**Comment by r3ggi** [comment]
Fixed in https://github.com/securing/IOSSecuritySuite/commit/ede30b2c76d97693aba30ce5d0bafe87744278b4. Please update the ISS to `1.9.4`
