### ISSUE TITLE
Saily Package Manager

### ISSUE THREAD

**Issue by Xenzofq** [securing/IOSSecuritySuite#63]
Please add the "apt-repo://" url scheme as the Saily Package Manager uses this scheme, this is another Cydia alternative just like Zebra, Installer 5, and Sileo.

**Comment by joshuah345** [comment]
https://github.com/SailyTeam/Saily (source code)

**Comment by r3ggi** [comment]
Hey @Xenzofq,

Thanks for your idea, however we're not gonna improve the `checkURLSchemes` method. AsIt may cause false positive issues ( take a look at https://github.com/securing/IOSSecuritySuite/issues/62 )
