### ISSUE TITLE
Question about the hashValue that is stored in the server

### ISSUE THREAD

**Issue by amineabiaba** [securing/IOSSecuritySuite#72]
Hello,
I need help. I want more explanation about this script :

> if let hashValue = IOSSecuritySuite.getMachOFileHashValue(.default), hashValue == "your-application-executable-hash-value" {
> print("I have not been Tampered.")
> }
> else {
> print("I have been Tampered.")
> }

I generate the hash value from executable file but it's not matching with the app generated value.

**Comment by r3ggi** [comment]
Hey,

How do you generate the hash of the executable? Are you sure it looks like this: `dd if=path_to_ipa_content/Payload/MyApp.app/MyApp ibs=1 skip=26408 count=0x0000000000030560 | shasum -a 256` where `skip` contains the offset of the `__text` section?
