### ISSUE TITLE
Can iOS Deployment Target be downgraded to 9.0?

### ISSUE THREAD

**Issue by CAMOBAP** [securing/IOSSecuritySuite#73]
According to my local tests, iOS deployment target can be safely downgraded from 10.0 to 9.0.

This is important for me because I would like to add `[IOSSecuritySuite](https://github.com/securing/IOSSecuritySuite)` as a dependency to an SDK (which has deployment target 9.0). Probably it may be useful for someone else.

*I can help with PR and GHA CI if need

**Comment by r3ggi** [comment]
Hey!

iOS 9.0 was introduced in 2015. I don't see the point of using ISS in such an old iOS version with so many vulnerabilities that won't be fixed. IMO deployment target set from 10.0 is really loose..
