### ISSUE TITLE
ReverseEngineeringToolsChecker needs more details for `amIReverseEngineered` method

### ISSUE THREAD

**Issue by sayler8182** [securing/IOSSecuritySuite#79]
Currently the `IOSSecuritySuite.amIReverseEngineered()` method return only the `Bool` value whether the app is potentially reverse engineered or not. 
Could You add more information what was detected ?
```
static func amIReverseEngineered() -> ReverseEngineeredStatus { ... }
```

eg. `IOSSecuritySuite.amIJailbrokenWithFailedChecks()` returns `JailbreakStatus` with `failMessage`

**Comment by r3ggi** [comment]
Hey!

That's a good idea! Feel free to create a PR. 🚀
