### ISSUE TITLE
M1 Mac detected as a jailbroken device

### ISSUE THREAD

**Issue by slawekp** [securing/IOSSecuritySuite#80]
Hi!

Unfortunately on M1 Mac the app with this library implemented now reports a jailbroken device. Is this something that came up before? Is there a fix or at least a workaround?

Thank you 🙇

**Comment by Tony-Y** [comment]
Did you see #77 ?

**Comment by r3ggi** [comment]
Hey!

We have no plans to add a functionality that detects if an app is running on macOS. ISS was created for iOS apps. If you want your app to be also compatible with macOS - it's recommended to disable ISS on Mac.
