### ISSUE TITLE
Why do not support iOS apps running on macOS

### ISSUE THREAD

**Issue by bokuhe** [securing/IOSSecuritySuite#81]
The name of this library is 'iOS' Security Suite.

iOS app can be run on macOS equipped with apple silicon.
This is an iOS app, not a macOS app.

If it does not support iOS running on macOS, should be named 'iPhoneSecuritySuite'.

If the iOSSecuritySuite doesn't support running iOS on macOS, how about giving a warning or error like 'macOS not supported' when calling methods such as amIJailbreak? Or how about updating this as a README

**Comment by bokuhe** [comment]
Who wants to run iOS on macOS can refer to my fork repository and use it.

`pod 'IOSSecuritySuite', :git => 'https://github.com/bokuhe/IOSSecuritySuite.git', :branch => 'feat/ios-app-on-mac'`

**Comment by r3ggi** [comment]
Hey!

For now we're not considering iOS apps launched on macOS - but the world changes and we may do it in the future. I'll update the README then if the current ISS use case is not clear.
