### ISSUE TITLE
Jailbreak check is failing because of missing Library paths in checkExistenceOfSuspiciousFiles() func

### ISSUE THREAD

**Issue by sanu** [securing/IOSSecuritySuite#86]
`amIJailbroken()` is returning false on a JailBreak device.

`checkExistenceOfSuspiciousFiles()` needs addition of below paths to fix the problem. Could you please update.

```
/Library/BawAppie/ABypass/
/Library/MobileSubstrate/DynamicLibraries/
/Library/PreferenceBundles/
```

**Comment by r3ggi** [comment]
Hey! Thank you for the information. ISS has been updated 🚀
