### ISSUE TITLE
Unable to detect Hestia tweak

### ISSUE THREAD

**Issue by luzsyn** [securing/IOSSecuritySuite#87]
Hestia, seems to be unable to detect jailbroken status.

Repo: [https://repo.icrazeios.com](https://repo.icrazeios.com/)

**Comment by luzsyn** [comment]
seems change paths of the suspicious libraries to 'no.txt100, notxt101, notxt102 ...'

**Comment by r3ggi** [comment]
Hey @luzsyn,

Thank you for the information. I'll take a look at it in a few weeks

**Comment by JulianBissekkou** [comment]
Any updates on this?

**Comment by Shafran123** [comment]
any update on this

**Comment by r3ggi** [comment]
Hey guys!

The new 1.9.8 version is resistant to the Hestia tweak 🔥

```
[Hestia] Loading Hestia into process biz.securing.FrameworkClientApp
[+] Am I jailbroken?: true
```
