### ISSUE TITLE
Use of unresolved identifier 'Self'

### ISSUE THREAD

**Issue by HariIDPal** [securing/IOSSecuritySuite#9]
I have check out your code and tried to compile it shows Use of unresolved identifier 'Self’.

_Below I have mentioned the issue details:
![Screenshot 2020-01-14 at 7 23 09 PM](https://user-images.githubusercontent.com/45866649/72349863-55139e00-3703-11ea-948c-d9c451e4aee7.png)
_

**Filename**: JailbreakChecker
**Line number**: 113
**Issue:** Syntax error in self 

Please check and update the code, thanks.

**Comment by r3ggi** [comment]
Redundant `Self` removed. Please check if now works for you :-)

**Comment by HariIDPal** [comment]
Thanks. Now it is working fine.
