### ISSUE TITLE
Library + Main Class name clash

### ISSUE THREAD

**Issue by DevAgani** [securing/IOSSecuritySuite#90]
~/ios/Pods/IOSSecuritySuite/IOSSecuritySuite/IOSSecuritySuite.swift:14:14: Public class 'IOSSecuritySuite.IOSSecuritySuite' shadows module 'IOSSecuritySuite', which may cause failures when importing 'IOSSecuritySuite' or its clients in some configurations; please rename either the class 'IOSSecuritySuite.IOSSecuritySuite' or the module 'IOSSecuritySuite', or see https://github.com/apple/swift/issues/56573 for workarounds

Version: 1.9.7

**Comment by r3ggi** [comment]
Hey,

Thanks for raising this issue. The library name AFAIK doesn't violate Swift naming module & class naming convention and the problem you mention is a bug in the Swift compiler. 

The bug reporter claims that the bug itself is rather rare:

> This problem is usually invisible until a client tries to read the module interface, which is rarely done in normal development workflows, so the invalid module interface may not be noticed until much later.

For ISS I don't see it breaks any functionality, so let's keep this library as it is.
