### ISSUE TITLE
Unable to detect mask.app

### ISSUE THREAD

**Issue by iOSPrincekin** [securing/IOSSecuritySuite#92]
used mask.app, seems to be unable to detect jailbroken status.

Repo: https://repo.xmkj.one  

[IR|Mask] mask.app

**Comment by iOSPrincekin** [comment]
http://apt.maskjb.com
you need to buy a registration code in the Taobao app or I can help you buy it!

**Comment by r3ggi** [comment]
Hey,

Thanks for the information. For now I don't plan to support paid tools
