### ISSUE TITLE
[IMP] Jailbreak detection failing on some device for url schema

### ISSUE THREAD

**Issue by ravindra-shetty** [securing/IOSSecuritySuite#93]
All of a sudden we started seeing jumps on jailbreak detection cases on our app. After checking the reason the checkURLSchemes method gets passed. After checking more it's getting detecting all of the url schemes on some of the devices. 

Something seems wrong here. I suspect that some apps on App Store added all of these url schemes on their **URL Types** List instead of **Queried URL Schemes**. 

Does anyone else observe the same issue? If yes any idea which app is this?

**Comment by r3ggi** [comment]
Hey!

Please make a notice that if in your region URL Schemes give you false positives - you can always use the `IOSSecuritySuite.amIJailbrokenWithFailedChecks()` method and ignore the `checkURLSchemes`
